# Generated by Django 5.2.5 on 2025-08-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicerun',
            options={'ordering': ['-final_score', '-created_at']},
        ),
    ]
