# Generated by Django 5.2.5 on 2025-08-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
