# Generated by Django 5.2.5 on 2025-08-14 07:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0006_alter_player_options_alter_practicerun_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('attempts_per_user', models.PositiveIntegerField(default=0)),
                ('min_participants', models.PositiveIntegerField(default=1)),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('prize1', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=12)),
                ('prize2', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('prize3', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('SETTLED', 'SETTLED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typingapp.center')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='typingapp.duration')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='typingapp.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='typingapp.level')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('accuracy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typingapp.center')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='typingapp.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('receipt', models.FileField(upload_to='receipts/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REFUNDED', 'REFUNDED')], default='SUBMITTED', max_length=10)),
                ('review_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='typingapp.contest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
